# Generated by Django 6.0.7 on 2026-08-05 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('core', '0001_initial'),
        ('students', '0002_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('TRANSFERRED', 'Transféré'), ('WITHDRAWN', 'Désisté'), ('GRADUATED', 'Diplômé')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('remarks', models.TextField(blank=True, verbose_name='Observations')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='classes.classroom', verbose_name='Classe')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.schoolyear', verbose_name='Année scolaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-school_year', 'classroom', 'student'],
                'unique_together': {('student', 'school_year')},
            },
        ),
    ]
