# Generated by Django 6.0.7 on 2026-08-06 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10, verbose_name='Jour')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Salle')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='classes.classroom', verbose_name='Classe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Emploi du temps',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
