# Generated by Django 6.0.7 on 2026-08-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ÉTABLISSEMENT SCOLAIRE', max_length=200, verbose_name="Nom de l'établissement")),
                ('city', models.CharField(default='Cameroun', max_length=100, verbose_name='Ville / Pays')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/', verbose_name='Logo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': "Paramètres de l'établissement",
                'verbose_name_plural': "Paramètres de l'établissement",
            },
        ),
    ]
