# Generated by Django 6.0.7 on 2026-08-04 07:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(choices=[(1, 'Séquence 1'), (2, 'Séquence 2'), (3, 'Séquence 3'), (4, 'Séquence 4'), (5, 'Séquence 5'), (6, 'Séquence 6')], verbose_name='Séquence')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note (/20)')),
                ('appreciation', models.CharField(blank=True, max_length=100, verbose_name='Appréciation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequence_grades_created', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_grades', to='core.schoolyear', verbose_name='Année scolaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_grades', to='students.student', verbose_name='Élève')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_grades', to='subjects.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Note de séquence',
                'verbose_name_plural': 'Notes de séquence',
                'ordering': ['student', 'subject', 'sequence'],
                'unique_together': {('student', 'subject', 'school_year', 'sequence')},
            },
        ),
    ]
