# Generated by Django 6.0.7 on 2026-08-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('TEACHER', 'Enseignant'), ('STUDENT', 'Élève'), ('PARENT', 'Parent')], default='STUDENT', max_length=20, verbose_name='Rôle'),
        ),
    ]
