# Generated by Django 6.0.7 on 2026-08-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Coefficient')),
                ('levels', models.ManyToManyField(related_name='subjects', to='classes.level', verbose_name='Niveaux concernés')),
                ('teachers', models.ManyToManyField(blank=True, related_name='subjects', to='teachers.teacher', verbose_name='Enseignants')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['name'],
            },
        ),
    ]
