# Generated by Django 6.0.7 on 2026-08-05 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('type', models.CharField(choices=[('ABSENCE', 'Absence'), ('RETARD', 'Retard')], max_length=10, verbose_name='Type')),
                ('status', models.CharField(choices=[('JUSTIFIED', 'Justifiée'), ('UNJUSTIFIED', 'Non justifiée')], default='UNJUSTIFIED', max_length=15, verbose_name='Statut')),
                ('reason', models.TextField(blank=True, verbose_name='Motif / Justification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.schoolyear', verbose_name='Année scolaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Absence / Retard',
                'verbose_name_plural': 'Absences / Retards',
                'ordering': ['-date'],
                'unique_together': {('student', 'date', 'type')},
            },
        ),
    ]
