# Generated by Django 6.0.7 on 2026-08-07 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'Absence', 'verbose_name_plural': 'Absences'},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name="Nombre d'heures"),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sequence',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Séquence 1'), (2, 'Séquence 2'), (3, 'Séquence 3'), (4, 'Séquence 4'), (5, 'Séquence 5'), (6, 'Séquence 6')], null=True, verbose_name='Séquence'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject', verbose_name='Matière'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='type',
        ),
    ]
